import Foundation
import Testing
import DuneIIContracts
import DuneIIFormats
import DuneIIWorld
import DuneIISimulation
@testable import DuneIIScenarios

/// Per-scenario golden vs OpenDUNE. Both engines load the shared `bootstrap.ini`, apply the same
/// simulated command stream, and dump per-unit state; this asserts our state equals the oracle's.
///
/// The oracle fixtures are generated by the `--parity-scenario` mode (see
/// `Documentation/Architecture/ScenarioHarness.md`), e.g.:
///   opendune --parity-scenario=99 --parity-cmd=move,22,2600 --parity-data-dir=<dir> --parity-dump=moving-golden.jsonl
/// where <dir> holds the install + `bootstrap.ini` as `SCENH099.INI`.
///
/// Currently the comparison covers **frame 0** (after load + commands, before ticking) — which verifies
/// our scenario loading + command pipeline against OpenDUNE's. The per-tick trajectory turns on as the
/// movement/combat natives land (the fixture format already carries every tick).
@Suite("Scenario golden vs OpenDUNE")
struct ScenarioGoldenTests {
    struct Frame: Decodable { let tick: Int; let units: [UnitState] }
    struct UnitState: Decodable, Equatable {
        let index: UInt16; let type: UInt8; let houseID: UInt8; let packed: UInt16; let orient: Int16
        let hp: UInt16; let actionID: UInt8; let targetMove: UInt16; let targetAttack: UInt16; let alive: Int
    }

    private func snapshot(_ s: GameState) -> [UnitState] {
        s.units.indices.filter { s.units[$0].o.flags.contains(.used) }.map { i in
            let u = s.units[i]
            return UnitState(index: u.o.index, type: u.o.type, houseID: u.o.houseID,
                             packed: u.o.position.packed, orient: Int16(u.orientation[0].current),
                             hp: u.o.hitpoints, actionID: u.actionID, targetMove: u.targetMove,
                             targetAttack: u.targetAttack, alive: u.o.flags.contains(.used) ? 1 : 0)
        }
    }

    @Test("moving: load + move command matches the oracle frame 0")
    func movingFrame0() throws {
        var repo = URL(fileURLWithPath: #filePath)
        for _ in 0 ..< 4 { repo.deleteLastPathComponent() }   // Code/Tests/ScenariosTests → repo root
        let fix = URL(fileURLWithPath: #filePath).deletingLastPathComponent().appendingPathComponent("Fixtures")
        guard let icon = try? Data(contentsOf: repo.appendingPathComponent("Resources/Tiles/Maps/ICON.MAP")),
              let emc = try? Data(contentsOf: repo.appendingPathComponent("Resources/Scripts/UNIT/UNIT.emc")),
              let ini = try? Data(contentsOf: fix.appendingPathComponent("bootstrap.ini")),
              let golden = try? String(contentsOf: fix.appendingPathComponent("moving-golden.jsonl"), encoding: .utf8)
        else { return }

        var state = GameState()
        state.loadScenario(ini: Ini(ini), iconMap: try IconMap(icon))

        // The placed tank, ordered to move to packed tile 2600 — the same command the oracle replayed.
        let tank = state.units.first { $0.o.flags.contains(.used) }!
        let orders = UnitOrders(scriptInfo: ScriptInfo(try Emc.Program(emc)))
        orders.apply(.move(unit: tank.o.index, tile: 2600), in: &state)

        let expected = try JSONDecoder().decode(Frame.self, from: Data(golden.split(separator: "\n")[0].utf8))
        #expect(expected.tick == 0)
        #expect(snapshot(state) == expected.units)
    }
}
